### ISSUE TITLE
台中/高雄市 URL失效了

### ISSUE THREAD

**Issue by bill-florio** [Kayxue/Youbike-API#1]
你好！我想回報這兩個URL已失效了：

    "臺中市": "    https://datacenter.taichung.gov.tw/swagger/OpenData/9af00e84-473a-4f3d-99be-b875d8e86256",
    "高雄市": "https://api.kcg.gov.tw/api/service/Get/b4dd9c40-9027-4125-8666-06bef1756092"

**Comment by Kayxue** [comment]
OK 我這幾天處理

**Comment by bill-florio** [comment]
想請教一下，是否每個縣市都有獨立的API? TDX 整合了各縣市的API, 但要申請API KEY...但有些市如新竹我找不到開放資料

**Comment by Kayxue** [comment]
應該是，不少都分開的
![IMG_2652](https://github.com/Kayxue/Youbike-API/assets/26020165/1751b734-e980-4c23-a9ca-d528dbfb3aec)
![IMG_2653](https://github.com/Kayxue/Youbike-API/assets/26020165/0baf4413-f441-4863-9e07-fc069e99baa4)

**Comment by Kayxue** [comment]
抱歉久等惹～～
台中部分確實好像失效了
高雄部分好像沒有問題喔🤔🤔🤔
![image](https://github.com/Kayxue/Youbike-API/assets/26020165/d354b0f0-b63e-4d5c-a7cd-64649a7f7d81)

**Comment by Kayxue** [comment]
恩～～高雄市的話那個可能是他們自己的 API 有點不太穩定
一小段時間以前好好的，現在突然開始丟 500
目前好像沒有看到有其他高雄市的 Youbike API 了

**Comment by Kayxue** [comment]
已修改並上傳 2.0.1 版本
若還有使用上的問題歡迎再次開 issue 詢問
